apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample-cron
  labels:
    name: some-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    metadata:
      labels:
        name: some-job
    spec:
      template:
        metadata:
          labels:
            name: some-pod
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello Kubernetes!!!"]
          restartPolicy: Never