apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
  labels:
    name: job-ramana
spec:
  template:
    metadata:
      name: countdown
      labels:
        name: Ramana
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i; sleep 10 ; done"
      restartPolicy: Never