apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: test-vol
          mountPath: /kube
  volumes:
  - name: test-vol
    persistentVolumeClaim:
        claimName: pvc-hostpath