apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-secret-vol
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: test-vol
      mountPath: "/app/cred"
      readOnly: true
  volumes:
  - name: test-vol
    secret:
      secretName: nginx-secret-vol
      items:
        - key: username.txt
          path: user.txt
        - key: password.txt
          path: pwd.txt