apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
    app: nginx
    env: uat
  annotations:
    owner: 'Ramana'
    email: 'ramana.yampala@gmail.com'  
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
  restartPolicy: Never
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"