apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
    app: nginx
    env: uat
  annotations:
    owner: 'Ramana'
    email: 'ramana.yampala@gmail.com'  
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
  restartPolicy: Never
  nodeSelector:
    env: "dev"