apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: john-sample-roleninding
  namespace: sample
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: john-sample
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: john